version: '3.8'

# Docker Compose configuration using Docker Hub images
# This file uses the images built and pushed by GitHub Actions

services:
  # Infrastructure Services
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: courier-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    networks:
      - courier-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 30s
      timeout: 10s
      retries: 3

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: courier-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_CONFLUENT_METRICS_ENABLE: 'true'
      KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - courier-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: courier-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: courier_db
      POSTGRES_USER: courier_user
      POSTGRES_PASSWORD: courier_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - courier-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U courier_user -d courier_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: courier-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - courier-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: courier-kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: courier-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - courier-network

  # Microservices from Docker Hub
  courier-main-service:
    image: ${DOCKER_USERNAME:-your-dockerhub-username}/courier-main-service:${IMAGE_TAG:-latest}
    container_name: courier-main-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SERVER_PORT: 8080
      DATABASE_URL: jdbc:postgresql://postgres:5432/courier_db
      DATABASE_USERNAME: courier_user
      DATABASE_PASSWORD: courier_pass
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      JWT_SECRET: courierMainServiceSecretKey2024!@#$%^&*()
      LOG_LEVEL: INFO
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./logs:/var/log/courier
    networks:
      - courier-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  courier-customer-interface:
    image: ${DOCKER_USERNAME:-your-dockerhub-username}/courier-customer-interface:${IMAGE_TAG:-latest}
    container_name: courier-customer-interface
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      courier-main-service:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SERVER_PORT: 8081
      DATABASE_URL: jdbc:postgresql://postgres:5432/courier_db
      DATABASE_USERNAME: courier_user
      DATABASE_PASSWORD: courier_pass
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      JWT_SECRET: courierCustomerInterfaceSecretKey2024!@#$%^&*()
      MAIN_SERVICE_URL: http://courier-main-service:8080
      LOG_LEVEL: INFO
      MAX_PARCELS_PER_DAY: 100
      RATE_LIMIT: 60
    volumes:
      - ./logs:/var/log/courier
    networks:
      - courier-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  courier-frontend:
    image: ${DOCKER_USERNAME:-your-dockerhub-username}/courier-frontend:${IMAGE_TAG:-latest}
    container_name: courier-frontend
    depends_on:
      courier-main-service:
        condition: service_healthy
      courier-customer-interface:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      REACT_APP_MAIN_API_URL: http://localhost:8080/api/v1
      REACT_APP_CUSTOMER_API_URL: http://localhost:8081/api/v1/customer
      REACT_APP_ENVIRONMENT: development
      REACT_APP_VERSION: ${IMAGE_TAG:-latest}
    networks:
      - courier-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Kafka topic initialization
  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ['/bin/sh', '-c']
    command: |
      "
      echo 'Waiting for Kafka to be ready...'
      kafka-topics --bootstrap-server kafka:29092 --list

      echo 'Creating topics for courier microservices...'
      
      # Main service topics (from EventStreamService configuration)
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic incoming-parcel-orders --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic abc-transport-events --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic abc-transport-responses --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic parcel-tracking-events --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic courier-internal-events --replication-factor 1 --partitions 3
      
      # Customer interface topics
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic customer-parcel-submissions --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic parcel-status-updates --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic customer-notifications --replication-factor 1 --partitions 3
      
      echo 'All topics created successfully:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "
    networks:
      - courier-network

volumes:
  zookeeper-data:
    driver: local
  zookeeper-logs:
    driver: local
  kafka-data:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
  courier-network:
    driver: bridge
    name: courier-microservices-network
