spring:
  application:
    name: courier-customer-interface-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  # Database configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/courier_db}
    username: ${DATABASE_USERNAME:courier_user}
    password: ${DATABASE_PASSWORD:courier_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
  
  # Kafka configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: customer-interface-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.courier.dto,com.courier.event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: false
        retries: 3
        acks: all
        enable.idempotence: true
  
  # Spring Cloud Stream configuration
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          auto-create-topics: true
          auto-add-partitions: true
      bindings:
        # Customer parcel submissions
        customerParcels-out-0:
          destination: customer-parcel-submissions
          content-type: application/json
          producer:
            partition-key-expression: headers['customerId']
        
        # Parcel status updates for customers
        parcelStatusUpdates-in-0:
          destination: parcel-status-updates
          content-type: application/json
          group: customer-interface-status-group
          consumer:
            auto-startup: true
        
        # Customer notifications
        customerNotifications-out-0:
          destination: customer-notifications
          content-type: application/json

# Server configuration
server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api/v1/customer
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  http2:
    enabled: true

# Security configuration
courier:
  app:
    jwtSecret: ${JWT_SECRET:customerInterfaceSecretKey2024!@#$%^&*()}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000} # 24 hours
    jwtRefreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7 days
  
  # Main service configuration for inter-service communication
  main-service:
    base-url: ${MAIN_SERVICE_URL:http://localhost:8080}
    timeout: ${MAIN_SERVICE_TIMEOUT:30s}
    retry:
      max-attempts: 3
      delay: 1s

# Management and monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,readiness,liveness
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    readiness:
      enabled: true
    liveness:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: courier-customer-interface-service
      environment: ${ENVIRONMENT:development}

# Logging configuration
logging:
  level:
    com.courier: ${LOG_LEVEL:INFO}
    org.springframework.kafka: WARN
    org.springframework.cloud.stream: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:/var/log/courier/customer-interface.log}

# Customer interface specific configuration
customer-interface:
  features:
    parcel-registration: ${PARCEL_REGISTRATION_ENABLED:true}
    parcel-tracking: ${PARCEL_TRACKING_ENABLED:true}
    notifications: ${NOTIFICATIONS_ENABLED:true}
    file-upload: ${FILE_UPLOAD_ENABLED:true}
  limits:
    max-parcels-per-day: ${MAX_PARCELS_PER_DAY:100}
    max-file-size: ${MAX_FILE_SIZE:10MB}
    rate-limit-requests-per-minute: ${RATE_LIMIT:60}
  notification:
    email:
      enabled: ${EMAIL_NOTIFICATIONS_ENABLED:true}
      from: ${EMAIL_FROM:noreply@courier.com}
    sms:
      enabled: ${SMS_NOTIFICATIONS_ENABLED:false}

# Resilience4j configuration for circuit breakers
resilience4j:
  circuitbreaker:
    instances:
      main-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
  retry:
    instances:
      main-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
  timelimiter:
    instances:
      main-service:
        timeout-duration: 30s
