apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "courier-microservices.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "courier-microservices.labels" . | nindent 4 }}
data:
  # Database configuration
  database.host: {{ .Values.database.host | quote }}
  database.port: {{ .Values.database.port | quote }}
  database.name: {{ .Values.database.name | quote }}
  database.username: {{ .Values.database.username | quote }}
  
  # Kafka configuration
  kafka.host: {{ .Values.messaging.kafka.host | quote }}
  kafka.port: {{ .Values.messaging.kafka.port | quote }}
  kafka.bootstrap.servers: {{ include "courier-microservices.kafkaBootstrapServers" . | quote }}
  
  # Redis configuration
  {{- if .Values.cache.redis.enabled }}
  redis.host: {{ .Values.cache.redis.host | quote }}
  redis.port: {{ .Values.cache.redis.port | quote }}
  {{- end }}
  
  # Environment configuration
  environment: {{ .Values.environment | quote }}
  namespace: {{ .Values.namespace | quote }}
  
  # Service URLs for inter-service communication
  main.service.url: "http://{{ .Values.mainService.name }}:{{ .Values.mainService.service.port }}"
  customer.interface.url: "http://{{ .Values.customerInterface.name }}:{{ .Values.customerInterface.service.port }}"
  frontend.url: "http://{{ .Values.frontend.name }}:{{ .Values.frontend.service.port }}"
  
  # Kafka topics configuration
  {{- if .Values.messaging.kafka.topics }}
  kafka.topics: |
    {{- range .Values.messaging.kafka.topics }}
    - name: {{ .name }}
      partitions: {{ .partitions }}
      replicationFactor: {{ .replicationFactor }}
    {{- end }}
  {{- end }}

---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "courier-microservices.fullname" . }}-monitoring-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "courier-microservices.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 30s
    
    scrape_configs:
    - job_name: 'courier-main-service'
      static_configs:
      - targets: ['{{ .Values.mainService.name }}:{{ .Values.mainService.port }}']
      metrics_path: '/actuator/prometheus'
      scrape_interval: 30s
    
    - job_name: 'courier-customer-interface'
      static_configs:
      - targets: ['{{ .Values.customerInterface.name }}:{{ .Values.customerInterface.port }}']
      metrics_path: '/actuator/prometheus'
      scrape_interval: 30s
    
    - job_name: 'courier-frontend'
      static_configs:
      - targets: ['{{ .Values.frontend.name }}:{{ .Values.frontend.port }}']
      metrics_path: '/health'
      scrape_interval: 30s
{{- end }}
