{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "courier-microservices.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "courier-microservices.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "courier-microservices.fullname" . }}-role
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "courier-microservices.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "courier-microservices.fullname" . }}-rolebinding
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "courier-microservices.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "courier-microservices.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "courier-microservices.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
